Atelier Numpy 
Contexte 
Une entreprise dispose de plusieurs capteurs installés dans différents bâtiments. Les capteurs 
mesurent régulièrement la température, l'humidité, la pression et la consommation énergétique. 
Les données doivent être préparées et analysées avant d'être transmises à un futur système de 
Machine Learning permettant de détecter des situations anormales

In [ ]:
temperatures_liste = [24.5, 25.1, 26.3, 27.0, 25.8]
temperatures_liste

[24.5, 25.1, 26.3, 27.0, 25.8]

2) Créer un tableau NumPy équivalent stockant ces températures ; 

In [3]:
import numpy as np
temp = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
temp

array([24.5, 25.1, 26.3, 27. , 25.8])

3) Effectuer une multiplication par 2 sur ces deux collections; 

-Pour les listes de Python

In [4]:
temperatures_liste2 = [24.5, 25.1, 26.3, 27.0, 25.8]* 2
temperatures_liste2

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]

- Pour les tableaux Numpy

In [5]:
temp2 = np.array([24.5, 25.1, 26.3, 27.0, 25.8]) *2
temp2

array([49. , 50.2, 52.6, 54. , 51.6])

4) Quelle différence observe-t-on ? 

La différence est que pour les liste de Python on observe un doublé de la liste au lieu d'effectuer l'opération comme pour le tableau de Numpy.

#      Partie 2 – Création des données 

1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro. 

In [6]:
import numpy as np
temperatures_zero = np.zeros(10)
print("1.", temperatures_zero)


1. [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2) Créer un tableau contenant 10 valeurs égales à 1. 

In [7]:
valeurs_un = np.ones(10)
print("2.", valeurs_un)

2. [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


3) Créer un tableau de 10 valeurs initialisées à 25. 

In [8]:
temperatures_25 = np.full(10, 25)

print(temperatures_25)

[25 25 25 25 25 25 25 25 25 25]


4) Créer une matrice identité de taille 5 × 5. 

In [10]:
matrice_identite = np.eye(5)

print(matrice_identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


5) Créer les 24 heures (de 0 à 23) de mesure d’une journée 

In [11]:
heures = np.arange(24)

print(heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C 

In [12]:
temperatures_regulieres = np.linspace(20, 30, 10)

print(temperatures_regulieres)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles 

In [13]:
np.random.seed(42)
temperatures_aleatoires = np.random.uniform(20, 30, 100)
print(temperatures_aleatoires)

[23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843
 24.56069984 27.85175961 21.99673782 25.14234438 25.92414569 20.46450413
 26.07544852 21.70524124 20.65051593 29.48885537 29.65632033 28.08397348
 23.04613769 20.97672114 26.84233027 24.40152494 21.22038235 24.9517691
 20.34388521 29.09320402 22.58779982 26.62522284 23.11711076 25.20068021
 25.46710279 21.84854456 29.69584628 27.75132823 29.39498942 28.9482735
 25.97899979 29.21874235 20.88492502 21.95982862 20.45227289 23.25330331
 23.8867729  22.71349032 28.28737509 23.56753327 22.8093451  25.42696083
 21.40924225 28.02196981 20.74550644 29.86886937 27.72244769 21.98715682
 20.05522117 28.15461428 27.06857344 27.29007168 27.71270347 20.74044652
 23.58465729 21.1586906  28.63103426 26.23298127 23.30

#   Partie 3 – Exploration des tableaux 

1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro. 

In [14]:
import numpy as np
np.random.seed(42)
temperatures = np.random.uniform(20, 35, 24)
print("Températures de la journée :")
print(temperatures)

Températures de la journée :
[25.61810178 34.2607146  30.97990913 28.97987726 22.34027961 22.33991781
 20.87125418 32.99264219 29.01672518 30.62108867 20.30876741 34.54864778
 32.48663961 23.18508666 22.72737451 22.75106765 24.56363364 27.87134647
 26.47917528 24.3684371  29.17779342 22.09240791 24.38216973 25.49542765]


2) Déterminer les propriétés suivantes du tableau 

a) nombre de dimensions 

In [15]:
print("Nombre de dimensions :", temperatures.ndim)

Nombre de dimensions : 1


b) nombre de valeurs ; 

In [16]:
print("Nombre de valeurs :", temperatures.size)

Nombre de valeurs : 24


c) type des données ; 

In [17]:
print("Type des données :", temperatures.dtype)

Type des données : float64


d) forme du tableau. 

In [18]:
print("Forme du tableau :", temperatures.shape)

Forme du tableau : (24,)


# Partie 4 – Indexation et slicing 

Considérant le tableau représentant les 24 températures d'une journée, afficher : 
1) la première mesure ;  

In [19]:
import numpy as np
np.random.seed(42)
temperatures = np.random.uniform(20, 35, 24)
print("Températures :")
print(temperatures)

Températures :
[25.61810178 34.2607146  30.97990913 28.97987726 22.34027961 22.33991781
 20.87125418 32.99264219 29.01672518 30.62108867 20.30876741 34.54864778
 32.48663961 23.18508666 22.72737451 22.75106765 24.56363364 27.87134647
 26.47917528 24.3684371  29.17779342 22.09240791 24.38216973 25.49542765]


2) la dernière mesure ;  

In [20]:
print("Dernière mesure :", temperatures[-1])

Dernière mesure : 25.495427649405375


3) la température de 8h ; 

In [21]:
print("Température à 8h :", temperatures[8])

Température à 8h : 29.01672517614813


4) les températures de 8h à 12h ;  

In [22]:
print("Températures de 8h à 12h :", temperatures[8:13])

Températures de 8h à 12h : [29.01672518 30.62108867 20.30876741 34.54864778 32.48663961]


5) les températures des 6 premières heures ;  

In [23]:
print("Températures des 6 premières heures :", temperatures[:6])

Températures des 6 premières heures : [25.61810178 34.2607146  30.97990913 28.97987726 22.34027961 22.33991781]


6) les températures des heures paires. 

In [25]:
print("Températures des heures paires :", temperatures[0:24:2])

Températures des heures paires : [25.61810178 30.97990913 22.34027961 20.87125418 29.01672518 20.30876741
 32.48663961 22.72737451 24.56363364 26.47917528 29.17779342 24.38216973]


# Partie 5 – Filtrage booléen 

Considérant le tableau représentant les 24 températures d'une journée, on souhaite détecter les 
situations inhabituelles.  
1) Afficher les températures supérieures à 30 °C 

In [26]:
import numpy as np
np.random.seed(42)
temperatures = np.random.uniform(20, 35, 24)
print("Températures :")
print(temperatures)

Températures :
[25.61810178 34.2607146  30.97990913 28.97987726 22.34027961 22.33991781
 20.87125418 32.99264219 29.01672518 30.62108867 20.30876741 34.54864778
 32.48663961 23.18508666 22.72737451 22.75106765 24.56363364 27.87134647
 26.47917528 24.3684371  29.17779342 22.09240791 24.38216973 25.49542765]


In [27]:
temperatures_sup_30 = temperatures[temperatures > 30]
print("Températures supérieures à 30 °C :")
print(temperatures_sup_30)

Températures supérieures à 30 °C :
[34.2607146  30.97990913 32.99264219 30.62108867 34.54864778 32.48663961]


2) Afficher les températures « normales » càd comprises entre 20 °C et 30 °C

In [28]:
temperatures_normales = temperatures[
    (temperatures >= 20) & (temperatures <= 30)
]
print("Températures normales :")
print(temperatures_normales)

Températures normales :
[25.61810178 28.97987726 22.34027961 22.33991781 20.87125418 29.01672518
 20.30876741 23.18508666 22.72737451 22.75106765 24.56363364 27.87134647
 26.47917528 24.3684371  29.17779342 22.09240791 24.38216973 25.49542765]


3) Supposons qu'une température supérieure à 35 °C soit considérée comme anormale. 
Déterminer anomalies, un tableau de booléen précisant les anomalies 

In [29]:
anomalies = temperatures > 35
print("Tableau des anomalies :")
print(anomalies)

Tableau des anomalies :
[False False False False False False False False False False False False
 False False False False False False False False False False False False]


4) Déterminer le nombre de températures anormales à l’aide de la variable anomalies  

In [30]:
nombre_anomalies = np.sum(anomalies)
print("Nombre de températures anormales :", nombre_anomalies)

Nombre de températures anormales : 0


# Partie 6 – Manipulation des dimensions 

On suppose qu’on a 5 capteurs.  
1) Créer aléatoirement la matrice représentant les températures mesurées par ces capteurs durant 
une journée 

In [31]:
import numpy as np
np.random.seed(42)
temperatures = np.random.uniform(20, 35, (5, 24))
print("Matrice des températures :")
print(temperatures)
print("\nForme de la matrice :", temperatures.shape)

Matrice des températures :
[[25.61810178 34.2607146  30.97990913 28.97987726 22.34027961 22.33991781
  20.87125418 32.99264219 29.01672518 30.62108867 20.30876741 34.54864778
  32.48663961 23.18508666 22.72737451 22.75106765 24.56363364 27.87134647
  26.47917528 24.3684371  29.17779342 22.09240791 24.38216973 25.49542765]
 [26.84104976 31.77763942 22.99510673 27.71351658 28.88621853 20.69675619
  29.11317278 22.55786186 20.97577389 34.23328306 34.4844805  32.12596022
  24.56920654 21.46508171 30.2634954  26.60228741 21.83057352 27.42765365
  20.51582782 33.63980603 23.88169972 29.93783427 24.67566614 27.80102032]
 [28.20065419 22.77281683 34.54376942 31.62699235 34.09248412 33.42241026
  28.96849968 33.82811353 21.32738753 22.93974294 20.67840933 24.87995496
  25.83015935 24.07023548 32.43106264 25.3512999  24.21401765 28.14044125
  22.11386337 32.03295471 21.11825966 34.80330405 31.58367154 22.98073522]
 [20.08283176 32.23192143 30.60286016 30.93510752 31.5690552  21.11066978
  25.376

2) Transformer la matrice en un tableau unidimensionnel

In [32]:
temperatures_1d = temperatures.flatten()
print("Tableau unidimensionnel :")
print(temperatures_1d)
print("\nForme :", temperatures_1d.shape)

Tableau unidimensionnel :
[25.61810178 34.2607146  30.97990913 28.97987726 22.34027961 22.33991781
 20.87125418 32.99264219 29.01672518 30.62108867 20.30876741 34.54864778
 32.48663961 23.18508666 22.72737451 22.75106765 24.56363364 27.87134647
 26.47917528 24.3684371  29.17779342 22.09240791 24.38216973 25.49542765
 26.84104976 31.77763942 22.99510673 27.71351658 28.88621853 20.69675619
 29.11317278 22.55786186 20.97577389 34.23328306 34.4844805  32.12596022
 24.56920654 21.46508171 30.2634954  26.60228741 21.83057352 27.42765365
 20.51582782 33.63980603 23.88169972 29.93783427 24.67566614 27.80102032
 28.20065419 22.77281683 34.54376942 31.62699235 34.09248412 33.42241026
 28.96849968 33.82811353 21.32738753 22.93974294 20.67840933 24.87995496
 25.83015935 24.07023548 32.43106264 25.3512999  24.21401765 28.14044125
 22.11386337 32.03295471 21.11825966 34.80330405 31.58367154 22.98073522
 20.08283176 32.23192143 30.60286016 30.93510752 31.5690552  21.11066978
 25.37698593 21.73803589 

3) Déterminer la transposée de la matrice 

In [33]:
temperatures_transposee = temperatures.T
print("Matrice transposée :")
print(temperatures_transposee)
print("\nForme :", temperatures_transposee.shape)

Matrice transposée :
[[25.61810178 26.84104976 28.20065419 20.08283176 27.84099244]
 [34.2607146  31.77763942 22.77281683 32.23192143 26.41311528]
 [30.97990913 22.99510673 34.54376942 30.60286016 20.3812869 ]
 [28.97987726 27.71351658 31.62699235 30.93510752 21.6183714 ]
 [22.34027961 28.88621853 34.09248412 31.5690552  20.47143779]
 [22.33991781 20.69675619 33.42241026 21.11066978 29.54615617]
 [20.87125418 29.11317278 28.96849968 25.37698593 24.71533972]
 [32.99264219 22.55786186 33.82811353 21.73803589 27.62856037]
 [29.01672518 20.97577389 21.32738753 32.94655139 33.61349711]
 [30.62108867 34.23328306 22.93974294 29.3494719  23.73938344]
 [20.30876741 34.4844805  20.67840933 24.96347037 26.15574385]
 [34.54864778 32.12596022 24.87995496 20.95337525 31.33326708]
 [32.48663961 24.56920654 25.83015935 24.66473483 23.43197248]
 [23.18508666 21.46508171 24.07023548 24.87774983 21.15469865]
 [22.72737451 30.2634954  32.43106264 30.94409268 24.34627179]
 [22.75106765 26.60228741 25.35129

4) Extraire toutes les mesures du capteur 1 ; 

In [34]:
capteur_1 = temperatures[0]
print("Mesures du capteur 1 :")
print(capteur_1)

Mesures du capteur 1 :
[25.61810178 34.2607146  30.97990913 28.97987726 22.34027961 22.33991781
 20.87125418 32.99264219 29.01672518 30.62108867 20.30876741 34.54864778
 32.48663961 23.18508666 22.72737451 22.75106765 24.56363364 27.87134647
 26.47917528 24.3684371  29.17779342 22.09240791 24.38216973 25.49542765]


5) Extraire toutes les mesures du capteur 5 ;

In [35]:
capteur_5 = temperatures[4]
print("Mesures du capteur 5 :")
print(capteur_5)

Mesures du capteur 5 :
[27.84099244 26.41311528 20.3812869  21.6183714  20.47143779 29.54615617
 24.71533972 27.62856037 33.61349711 23.73938344 26.15574385 31.33326708
 23.43197248 21.15469865 24.34627179 22.41831931 33.94546479 32.12180569
 29.50105635 33.07190885 32.05508115 22.79855088 33.38838498 28.09013363]


6) Extraire les mesures de tous les capteurs à 10h ; 

In [36]:
temperatures_10h = temperatures[:, 10]
print("Températures de tous les capteurs à 10h :")
print(temperatures_10h)

Températures de tous les capteurs à 10h :
[20.30876741 34.4844805  20.67840933 24.96347037 26.15574385]


7) Extraire les mesures des capteurs 2 à 4 entre 8h et 12h. 

In [37]:
mesures = temperatures[1:4, 8:13]
print("Mesures des capteurs 2 à 4 entre 8h et 12h :")
print(mesures)

Mesures des capteurs 2 à 4 entre 8h et 12h :
[[20.97577389 34.23328306 34.4844805  32.12596022 24.56920654]
 [21.32738753 22.93974294 20.67840933 24.87995496 25.83015935]
 [32.94655139 29.3494719  24.96347037 20.95337525 24.66473483]]


# Partie 7 – Concaténation 

On suppose qu’on a un 2nd bâtiment avec 3 capteurs.  
1) Créer aléatoirement la matrice représentant les températures mesurées par les 3 capteurs

In [38]:
import numpy as np
np.random.seed(100)
temperatures_batiment2 = np.random.uniform(20, 35, (3, 24))
print("Matrice du 2ème bâtiment :")
print(temperatures_batiment2)
print("Forme :", temperatures_batiment2.shape)

Matrice du 2ème bâtiment :
[[28.15107413 24.17554078 26.36776386 32.67164198 20.07078284 21.82353681
  30.06123627 32.38779133 22.05059885 28.62639994 33.36982931 23.13803183
  22.77992329 21.62565336 23.29546239 34.67935677 32.17524724 22.57911519
  32.24337123 24.11110621 26.47556275 34.10044729 32.26474068 25.04167925]
 [22.63115681 25.59248069 20.08532761 23.7863953  31.93493763 20.22882457
  28.98265065 29.05706809 21.57721528 25.72915167 20.54714085 33.35617345
  34.71381286 20.89912983 33.35818917 28.65352249 31.13719534 29.45275905
  28.72763289 20.30658698 23.15039867 28.17027317 31.53672757 23.76042844]
 [24.28843536 32.78592632 34.6250974  33.2727994  25.39261766 28.98288419
  25.32193417 25.10285323 22.67121484 23.56541313 20.67293424 27.58147144
  25.64378681 28.89208101 29.44912813 22.13900472 34.00761949 34.19569821
  29.03444987 25.8164942  25.44782006 23.06517915 24.15147592 23.69803822]]
Forme : (3, 24)


2) Déterminer de deux manières différentes la matrice qui fusionne les températures mesurées par 
les 8 capteurs durant une journée 


-      Premiere methode

In [39]:
temperatures_8_capteurs = np.concatenate(
    (temperatures, temperatures_batiment2),
    axis=0
)
print("Matrice des 8 capteurs :")
print(temperatures_8_capteurs)
print("Forme :", temperatures_8_capteurs.shape)

Matrice des 8 capteurs :
[[25.61810178 34.2607146  30.97990913 28.97987726 22.34027961 22.33991781
  20.87125418 32.99264219 29.01672518 30.62108867 20.30876741 34.54864778
  32.48663961 23.18508666 22.72737451 22.75106765 24.56363364 27.87134647
  26.47917528 24.3684371  29.17779342 22.09240791 24.38216973 25.49542765]
 [26.84104976 31.77763942 22.99510673 27.71351658 28.88621853 20.69675619
  29.11317278 22.55786186 20.97577389 34.23328306 34.4844805  32.12596022
  24.56920654 21.46508171 30.2634954  26.60228741 21.83057352 27.42765365
  20.51582782 33.63980603 23.88169972 29.93783427 24.67566614 27.80102032]
 [28.20065419 22.77281683 34.54376942 31.62699235 34.09248412 33.42241026
  28.96849968 33.82811353 21.32738753 22.93974294 20.67840933 24.87995496
  25.83015935 24.07023548 32.43106264 25.3512999  24.21401765 28.14044125
  22.11386337 32.03295471 21.11825966 34.80330405 31.58367154 22.98073522]
 [20.08283176 32.23192143 30.60286016 30.93510752 31.5690552  21.11066978
  25.37698

-          Deuxieme methode

In [40]:
temperatures_8_capteurs_v2 = np.vstack(
    (temperatures, temperatures_batiment2)
)
print("Matrice des 8 capteurs :")
print(temperatures_8_capteurs_v2)
print("Forme :", temperatures_8_capteurs_v2.shape)

Matrice des 8 capteurs :
[[25.61810178 34.2607146  30.97990913 28.97987726 22.34027961 22.33991781
  20.87125418 32.99264219 29.01672518 30.62108867 20.30876741 34.54864778
  32.48663961 23.18508666 22.72737451 22.75106765 24.56363364 27.87134647
  26.47917528 24.3684371  29.17779342 22.09240791 24.38216973 25.49542765]
 [26.84104976 31.77763942 22.99510673 27.71351658 28.88621853 20.69675619
  29.11317278 22.55786186 20.97577389 34.23328306 34.4844805  32.12596022
  24.56920654 21.46508171 30.2634954  26.60228741 21.83057352 27.42765365
  20.51582782 33.63980603 23.88169972 29.93783427 24.67566614 27.80102032]
 [28.20065419 22.77281683 34.54376942 31.62699235 34.09248412 33.42241026
  28.96849968 33.82811353 21.32738753 22.93974294 20.67840933 24.87995496
  25.83015935 24.07023548 32.43106264 25.3512999  24.21401765 28.14044125
  22.11386337 32.03295471 21.11825966 34.80330405 31.58367154 22.98073522]
 [20.08283176 32.23192143 30.60286016 30.93510752 31.5690552  21.11066978
  25.37698