Atelier Numpy 
Contexte 
Une entreprise dispose de plusieurs capteurs installés dans différents bâtiments. Les capteurs 
mesurent régulièrement la température, l'humidité, la pression et la consommation énergétique. 
Les données doivent être préparées et analysées avant d'être transmises à un futur système de 
Machine Learning permettant de détecter des situations anormales

In [ ]:
temperatures_liste = [24.5, 25.1, 26.3, 27.0, 25.8]
temperatures_liste

[24.5, 25.1, 26.3, 27.0, 25.8]

2) Créer un tableau NumPy équivalent stockant ces températures ; 

In [3]:
import numpy as np
temp = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
temp

array([24.5, 25.1, 26.3, 27. , 25.8])

3) Effectuer une multiplication par 2 sur ces deux collections; 

-Pour les listes de Python

In [4]:
temperatures_liste2 = [24.5, 25.1, 26.3, 27.0, 25.8]* 2
temperatures_liste2

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]

- Pour les tableaux Numpy

In [5]:
temp2 = np.array([24.5, 25.1, 26.3, 27.0, 25.8]) *2
temp2

array([49. , 50.2, 52.6, 54. , 51.6])

4) Quelle différence observe-t-on ? 

La différence est que pour les liste de Python on observe un doublé de la liste au lieu d'effectuer l'opération comme pour le tableau de Numpy.

#      Partie 2 – Création des données 

1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro. 

In [6]:
import numpy as np
temperatures_zero = np.zeros(10)
print("1.", temperatures_zero)


1. [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2) Créer un tableau contenant 10 valeurs égales à 1. 

In [7]:
valeurs_un = np.ones(10)
print("2.", valeurs_un)

2. [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


3) Créer un tableau de 10 valeurs initialisées à 25. 

In [8]:
temperatures_25 = np.full(10, 25)

print(temperatures_25)

[25 25 25 25 25 25 25 25 25 25]


4) Créer une matrice identité de taille 5 × 5. 

In [10]:
matrice_identite = np.eye(5)

print(matrice_identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


5) Créer les 24 heures (de 0 à 23) de mesure d’une journée 

In [11]:
heures = np.arange(24)

print(heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C 

In [12]:
temperatures_regulieres = np.linspace(20, 30, 10)

print(temperatures_regulieres)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles 

In [13]:
np.random.seed(42)
temperatures_aleatoires = np.random.uniform(20, 30, 100)
print(temperatures_aleatoires)

[23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843
 24.56069984 27.85175961 21.99673782 25.14234438 25.92414569 20.46450413
 26.07544852 21.70524124 20.65051593 29.48885537 29.65632033 28.08397348
 23.04613769 20.97672114 26.84233027 24.40152494 21.22038235 24.9517691
 20.34388521 29.09320402 22.58779982 26.62522284 23.11711076 25.20068021
 25.46710279 21.84854456 29.69584628 27.75132823 29.39498942 28.9482735
 25.97899979 29.21874235 20.88492502 21.95982862 20.45227289 23.25330331
 23.8867729  22.71349032 28.28737509 23.56753327 22.8093451  25.42696083
 21.40924225 28.02196981 20.74550644 29.86886937 27.72244769 21.98715682
 20.05522117 28.15461428 27.06857344 27.29007168 27.71270347 20.74044652
 23.58465729 21.1586906  28.63103426 26.23298127 23.30

#   Partie 3 – Exploration des tableaux 

1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro. 

In [14]:
import numpy as np
np.random.seed(42)
temperatures = np.random.uniform(20, 35, 24)
print("Températures de la journée :")
print(temperatures)

Températures de la journée :
[25.61810178 34.2607146  30.97990913 28.97987726 22.34027961 22.33991781
 20.87125418 32.99264219 29.01672518 30.62108867 20.30876741 34.54864778
 32.48663961 23.18508666 22.72737451 22.75106765 24.56363364 27.87134647
 26.47917528 24.3684371  29.17779342 22.09240791 24.38216973 25.49542765]


2) Déterminer les propriétés suivantes du tableau 

a) nombre de dimensions 

In [15]:
print("Nombre de dimensions :", temperatures.ndim)

Nombre de dimensions : 1


b) nombre de valeurs ; 

In [16]:
print("Nombre de valeurs :", temperatures.size)

Nombre de valeurs : 24


c) type des données ; 

In [17]:
print("Type des données :", temperatures.dtype)

Type des données : float64


d) forme du tableau. 

In [18]:
print("Forme du tableau :", temperatures.shape)

Forme du tableau : (24,)


# Partie 4 – Indexation et slicing 

Considérant le tableau représentant les 24 températures d'une journée, afficher : 
1) la première mesure ;  

In [19]:
import numpy as np
np.random.seed(42)
temperatures = np.random.uniform(20, 35, 24)
print("Températures :")
print(temperatures)

Températures :
[25.61810178 34.2607146  30.97990913 28.97987726 22.34027961 22.33991781
 20.87125418 32.99264219 29.01672518 30.62108867 20.30876741 34.54864778
 32.48663961 23.18508666 22.72737451 22.75106765 24.56363364 27.87134647
 26.47917528 24.3684371  29.17779342 22.09240791 24.38216973 25.49542765]


2) la dernière mesure ;  

In [20]:
print("Dernière mesure :", temperatures[-1])

Dernière mesure : 25.495427649405375


3) la température de 8h ; 

In [21]:
print("Température à 8h :", temperatures[8])

Température à 8h : 29.01672517614813


4) les températures de 8h à 12h ;  

In [22]:
print("Températures de 8h à 12h :", temperatures[8:13])

Températures de 8h à 12h : [29.01672518 30.62108867 20.30876741 34.54864778 32.48663961]


5) les températures des 6 premières heures ;  

In [23]:
print("Températures des 6 premières heures :", temperatures[:6])

Températures des 6 premières heures : [25.61810178 34.2607146  30.97990913 28.97987726 22.34027961 22.33991781]


6) les températures des heures paires. 

In [25]:
print("Températures des heures paires :", temperatures[0:24:2])

Températures des heures paires : [25.61810178 30.97990913 22.34027961 20.87125418 29.01672518 20.30876741
 32.48663961 22.72737451 24.56363364 26.47917528 29.17779342 24.38216973]
